server {
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index nutriwise_smart_food_advisor.html;
        try_files $uri $uri/ /nutriwise_smart_food_advisor.html;
    }
}
